Traceback (most recent call last):
  File "/rds/general/user/kl3620/home/FYP/fed_sim/src/main.py", line 60, in <module>
    global_model = SimCLR(args=args).to(device)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/kl3620/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/kl3620/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/rds/general/user/kl3620/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/rds/general/user/kl3620/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/rds/general/user/kl3620/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
           ^^^^^
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

